// <auto-generated />
using System;
using DemoAPIAzure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoAPIAzure.Migrations
{
    [DbContext(typeof(JobContext))]
    [Migration("20220925004515_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DemoAPIAzure.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("7c2196e4-9d06-4574-a212-d4bdef0a4bfb"),
                            Name = "Things to buy",
                            Weight = 20
                        },
                        new
                        {
                            CategoryId = new Guid("7c2196e4-9d06-4574-a212-d4bdef0a4bfc"),
                            Name = "Platzi courses to do",
                            Weight = 50
                        });
                });

            modelBuilder.Entity("DemoAPIAzure.Models.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("JobId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Job", (string)null);

                    b.HasData(
                        new
                        {
                            JobId = new Guid("8c2196e4-9d06-4574-a212-d4bdef0a4bfa"),
                            CategoryId = new Guid("7c2196e4-9d06-4574-a212-d4bdef0a4bfb"),
                            CreationDate = new DateTime(2022, 9, 24, 21, 45, 14, 613, DateTimeKind.Local).AddTicks(2936),
                            Priority = 1,
                            Title = "Milk"
                        },
                        new
                        {
                            JobId = new Guid("8c2196e4-9d06-4574-a212-d4bdef0a4bfb"),
                            CategoryId = new Guid("7c2196e4-9d06-4574-a212-d4bdef0a4bfb"),
                            CreationDate = new DateTime(2022, 9, 24, 21, 45, 14, 613, DateTimeKind.Local).AddTicks(2967),
                            Priority = 2,
                            Title = "Dog food"
                        },
                        new
                        {
                            JobId = new Guid("8c2196e4-9d06-4574-a212-d4bdef0a4bfc"),
                            CategoryId = new Guid("7c2196e4-9d06-4574-a212-d4bdef0a4bfc"),
                            CreationDate = new DateTime(2022, 9, 24, 21, 45, 14, 613, DateTimeKind.Local).AddTicks(2975),
                            Priority = 2,
                            Title = "Kubernetes"
                        },
                        new
                        {
                            JobId = new Guid("8c2196e4-9d06-4574-a212-d4bdef0a4bfd"),
                            CategoryId = new Guid("7c2196e4-9d06-4574-a212-d4bdef0a4bfc"),
                            CreationDate = new DateTime(2022, 9, 24, 21, 45, 14, 613, DateTimeKind.Local).AddTicks(2984),
                            Priority = 2,
                            Title = "New Relic"
                        },
                        new
                        {
                            JobId = new Guid("8c2196e4-9d06-4574-a212-d4bdef0a4bfe"),
                            CategoryId = new Guid("7c2196e4-9d06-4574-a212-d4bdef0a4bfc"),
                            CreationDate = new DateTime(2022, 9, 24, 21, 45, 14, 613, DateTimeKind.Local).AddTicks(2989),
                            Priority = 2,
                            Title = "Azure Databases"
                        });
                });

            modelBuilder.Entity("DemoAPIAzure.Models.Job", b =>
                {
                    b.HasOne("DemoAPIAzure.Models.Category", "Category")
                        .WithMany("Jobs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DemoAPIAzure.Models.Category", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
